thegreenwebfoundation/admin-portal

apps/accounts/management/commands/amend_hostingproviders_stats.py
Note to reader: deleting a hostingprovider checks all relations, which means deleting one provider is fairly slow due to the huge greencheck table.
=> Amend hostingproviders_stats so that we can remove hostingproviders in admin

apps/accounts/management/commands/migrate_approvals_idorig_to_null.py, apps/greencheck/admin.py, apps/greencheck/models.py
Gets you a list view for both ip and asn approvals so you can find the approvals easier. Part of this, is that we need to run a migration to replace 0 with null. If we don't do this, it will bark when you save an approval.
=> Add listview for approvals

apps/accounts/admin.py, apps/accounts/forms.py, apps/accounts/templates/emails/additional-info.txt, apps/accounts/templates/emails/info.txt, apps/accounts/templates/emails/pending-removal.txt
This adds a way to filter for hosts that are shown on the website in admin plus it lets you order by how many ip ranges are registered. (There are several hosts that have 0 ip ranges). 
I've also added the emails that Rene wrote up.
=> Add filter for admin and sending out of email

apps/accounts/admin_site.py, apps/accounts/templates/logout.html
This allows us to modify the template when a user logs out. Rene wished that we displayed the banner when someone logged out, and that we customized the message to say that we thanked them for spending time at the green web foundation web site.
=> Change the logout template to include copy and image

apps/accounts/admin.py
Because we couldn't migrate the table properly, we can't use the logging functionality for communication right now. 
See the following issue that tracks this more closely: https://github.com/thegreenwebfoundation/thegreenwebfoundation/issues/39
=> Comment out hosting communication for the time being

.gitignore, apps/greencheck/management/commands/create_greencheck_trigger.py, apps/greencheck/management/commands/insert_procedures.py, apps/greencheck/templates/backfill_procedure.sql, apps/greencheck/templates/insert_url_procedure.sql, apps/greencheck/templates/presenting.sql, greenweb/settings/common.py
This PR does the following
- Add the green_presenting table. URLs are unique. 
- Create a procedure for inserting urls into green_presenting. If the inserted url is not green we try to delete it. If the url is green we try to insert it. If it already exists (urls are unique, we update the date instead). 
- A backfill procedure to run to backfill the table `green_presenting`. 
- A trigger for the greencheck table, once the trigger is active it will push new urls into green_presenting.
=> Create procedures with management command

ansible/deploy.yml, ansible/inventories/prod, ansible/inventories/staging, apps/greencheck/management/commands/insert_procedures.py, apps/greencheck/templates/add_latest_check_for_url_procedure.sql, apps/greencheck/templates/backfill_by_url_procedure.sql, apps/greencheck/templates/load_in_csv.sql, apps/greencheck/url2green.py
This PR adds a slightly different approach for backfilling the data into the green urls data, in the `green_presenting` table.
This consists of
- a new stored procedure, `add_latest_check_for_url` to add the latest result for a given url from the `greencheck` table. This looks for the latest check in backwards, rather than going through all urls, over the last N years until we find the latest check. Save work with a transaction when we _do_ find a url, so we can resume if need be. 
- second stored procedure, `backfill_by_url` to loop through a set of urls in a table, using this new `add_latest_check_for_url` procedure
- some python functions for cleaning a list distinct urls we might get from the main greencheck table, to strip out invalid hostnames - I used this when checking different …
=> WIP - Update data cleaning scripts

apps/accounts/views.py
We add the hostingprovider and the datacenter group to new users. I also saw that we had hardcoded the success url so that is now removed.
=> Add hostingprovider and datacenter group to new users

apps/accounts/admin.py, apps/greencheck/models.py
The underlying issue was that when admin rendered the field. We had the following function being executed. 
```
def display_for_field(value, field, empty_value_display):
from django.contrib.admin.templatetags.admin_list import _boolean_icon
if getattr(field, 'flatchoices', None):
return dict(field.flatchoices).get(value, empty_value_display)
elif isinstance(field, models.BooleanField):
return _boolean_icon(value)
elif value is None:
return empty_value_display
elif isinstance(field, models.DateTimeField):
return formats.localize(timezone.template_localtime(value))
elif isinstance(field, (models.DateField, models.TimeField)):
return formats.localize(value)
elif isinstance(field, models.DecimalField):
return formats.number_format(value, field.decimal_places)
elif isinstance(field, …
```
=> Inherit from field instead of DecimalField

apps/greencheck/forms.py
Right now, non-staff users get a 500 when they try to update info about an ASN.
This make it possible for them to make requests with ASN numbers again
=> Add missing mixin to allow ASN submissions

apps/accounts/migrations/0001_initial.py, apps/accounts/models/hosting.py
An error was recently triggered -> https://sentry.io/organizations/product-science/issues/1501302817/?project=2071451&referrer=alert_email
Approved should be set by default here. I checked that the migration did not create any database changes by doing sqlmigrate. 
So there we can make these changes in the initial migration to avoid migration bloat.
=> Approved should be set by default

apps/accounts/admin_site.py, apps/accounts/templates/try_out.html
The definition signature needs to accept kwargs as seen in the issue on sentry -> https://sentry.io/share/issue/ec0022e3308d4f6cad10856d88794db1/
See also: https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/views/generic/edit.py#L63
=> Correct signature for check url

.travis.yml, Pipfile, Pipfile.lock, apps/greencheck/fixtures/ip_ranges.json, apps/greencheck/management/commands/update_aws_ip_ranges.py, apps/greencheck/models.py, apps/greencheck/test_aws_cloud_importer.py, apps/greencheck/test_models.py, conftest.py, greenweb/settings/testing.py, pytest.ini, run-tests.sh
This PR adds a few things
We now have a test harness for future development. I needed this to catch a hard to diagnose bug with the new IpAddress field implemented earlier.
We also have management command to run imports from public listings of IP ranges, as listed in issue 18 on the green web foundation.
https://github.com/thegreenwebfoundation/thegreenwebfoundation/issues/18
This updates the 5 regions listed as green/sustainable by Amazon, and imports their IPs.
*Overlapping IP ranges now that we have data direct from AWS* - We've seen bugs already where the API has been expecting just a single response back, when checking if a domain has an IP inside a given IP address. You can see this documented in issue 48 on the TGWF repo as described below: …
=> Add importer for publicly listed IP addresses for AWS

ansible/inventories/prod, ansible/inventories/staging, ansible/migrate.yml, apps/accounts/models/test_models.py
This adds a migration command with ansible, to avoid the need to sign in to run this management task in future.
Since adding the extra caching layer, it also adds the new server names
=> Ca add migrate cmd

makefile
This PR introduces release tracking, using sentry's CLI, so we can better tell when releases introduce issues and bugs, and alternatively when they fix them
https://docs.sentry.io/cli/
=> Add release command for make file

apps/accounts/filters.py, apps/accounts/models/user.py, apps/greencheck/management/commands/update_top_url_list.py, apps/greencheck/test_green_updater.py
This PR _removes_ timezone awareness, after discovering that because we're using TIMESTAMP in
a few places, and it's not compatible with timezone aware-mode, it's easier to make a change here, than change mahoosive tables. Check the docs here:
> #### TIMESTAMP columns
> 
> If you are using a legacy database that contains TIMESTAMP columns, you must set [USE\_TZ = False](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-USE_TZ) to avoid data corruption. [inspectdb](https://docs.djangoproject.com/en/3.1/ref/django-admin/#django-admin-inspectdb) maps these columns to [DateTimeField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.DateTimeField "django.db.models.DateTimeField") and if you enable timezone support, both MySQL and Django will attempt to …
=> Remove timezone awareness in admin

apps/greencheck/serializers.py, apps/greencheck/test_api.py, apps/greencheck/test_serializers.py, apps/greencheck/viewsets.py
This PR introduces the following changes:
- we filter the logged in API view now, to only allow IP ranges to be added to hosting providers a user belongs so.
- we have tests that check that our delete function sets an ip range to inactive, but does not delete them (we do this so we can relate historical greenchecks to IP ranges that used to belong to a given hosting provider at the time)
- we remove the `active` property from the API, as it's for internal use.
=> WIP - Update our delete function, and tidy up admin view

apps/accounts/models/hosting.py, apps/greencheck/forms.py, apps/greencheck/models.py, apps/greencheck/templates/flag_for_review_text.html, apps/greencheck/templates/flag_for_review_text.txt, apps/greencheck/tests/test_models.py, conftest.py, greenweb/settings/common.py, greenweb/settings/development.py
This PR introduces a notification system, in which emails are send to a support address when members update IP range or ASNs relating to their hosting provider.
This should make it easier to respond to member requests quickly, when they come in. We have some basic logic to avoid sending duplicate alerts - once a hosting provider has outstanding IP range or ASN requests no further emails are sent.
We have a basic email template in text and html, but there is no real styling applied- just links back to the hosting provider are provided.
=> Add notifcation support for when new IP Ranges and ASNs are added by member users

apps/greencheck/tests/test_api_greendomain.py, apps/greencheck/viewsets.py
This PR adds support for checking domains using a comma separated string, of the form a get param like `url=first.greendomain,second.greendomain.org,thirdgreen.co.uk`, or as a POST payload of the form:
```
[
"first.greendomain",
"second.greendomain.org",
"thirdgreen.co.uk"
]
```
The idea here is to allow for simple GET requests like we do in the browser extension, but when we have a large list, we can send a json array of domains as a POST too.
=> Add multiple domain checking

apps/greencheck/api/legacy_image_view.py, apps/greencheck/domain_check.py, apps/greencheck/models.py, apps/greencheck/tests/test_legacy_images.py, apps/greencheck/viewsets.py
We have an async worker that updates the caches, because to cope with load, we try to fetch from caches where possible over doing an expensive network lookup.
Normally this works okay, and means we can keep up with load, but in some cases we _do_ want to run a full lookup.
This introduces a `nocache` param to use for images and end results.
=> Add nocache option, to avoid waiting for workers

apps/greencheck/domain_check.py, apps/greencheck/legacy_workers.py, apps/greencheck/models.py, apps/greencheck/tests/__init__.py, apps/greencheck/tests/test_green_domain_dump.py, apps/greencheck/workers.py
This PR addresses two main causes of errors brought by our worker processes - when an api call to look up the 'localhost' domain is sent, and when we see a domain that points to an IP address that can't be resolved to a AS number using the Cymru IP to ASN service.
=> Re-arrange workers, and add checks for common logger errors

apps/greencheck/viewsets.py
We're getting some bad domain submissions that trigger a 500.
This catches the common errors, serving a non 500 result.
Were probably better serving a 400 Bad Request, but I think this is at least consistent with the old API.
=> Catch domain submissions that trigger UnicodeError

apps/greencheck/api/legacy_views.py, apps/greencheck/tests/__init__.py, apps/greencheck/tests/test_legacy_directory.py
This fixes the ordering since swapping out the PHP backend with the django version.
The PHP directory listing would provider listings in alphabetical order, but with partners listed first.
This reinstates this ordering.
=> Add fix for ordering

apps/accounts/admin.py, apps/greencheck/admin.py, apps/greencheck/forms.py
I saw an error in Sentry caused by some of the django choices still using the lower case options i.e. `action = ActionChoice.update` instead of `action = ActionChoice.UPDATE`.
This fixes the outstanding ones.
=> Make sure we're using constants in forms

apps/greencheck/workers.py
This should address the race condition we sometimes see when one process has started a transaction, to create an url or update it, and another process starts trying to update the same domain.
=> Switch to using the more idiomatic get-or-create for updating url information

apps/greencheck/domain_check.py, apps/greencheck/tests/test_domain_checker.py
In some cases, the service we rely on to resolve an AS network from an IP address returns an empty result.
This should account for the cases when we have this empty information.
=> Add a safety check for when we get a None result when resolving IPs to ASNs

apps/greencheck/api/legacy_views.py, apps/greencheck/tests/test_legacy_images.py, apps/greencheck/tests/test_legacy_v2_api.py
We get 500's when the browser extensions send a multi-url request. 
this stops the 500s happening.
=> Add checks for API error responses for browser extension multi checks

apps/theme/templatetags/admin_helpers.py, templates/admin/accounts/datacenter/fieldset.html, templates/admin/accounts/hostingprovider/hosting_provider_fieldset.html
For internal staff, this adds a link to check a domain against RIPE's handy stat checker.
This surfaces lots of useful info, including the AS number, the whois data, and the reverse hostname - useful for checking if a state is being served from a content delivery network.
=> Add handy RIPE check

ansible/templates/run_worker.sh.j2, apps/greencheck/viewsets.py, apps/greencheck/workers.py
Previously we had supervisor starting a job to speak to the legacy system.
This uses the correct queue workers.
=> Update the workers managed by supervisorctl

ansible/deploy.yml
This PR adds the missing step for generating bundles using rollup, before running collectstatic.
This should resolve the issue where link to non-existent js bundle
=> Add the missing step to generate our JS bundle

.github/workflows/run-tests.yml, apps/greencheck/management/commands/backfill_stats.py, apps/greencheck/models/stats.py, apps/greencheck/tasks.py, apps/greencheck/tests/models/test_greencheck_stats.py, apps/greencheck/tests/views/test_stats_view.py, greenweb/settings/common.py, pytest.ini
This PR adds a second queue so it's possible to see the state of long running jobs, of the kind used to generate stats and rankings.
=> Add second named queue for slower stats jobs

apps/accounts/admin.py, apps/greencheck/admin.py, apps/greencheck/models/checks.py, apps/greencheck/tests/models/test_greencheck_stats.py, apps/greencheck/tests/test_models.py, templates/admin/accounts/hostingprovider/change_form.html, templates/admin/accounts/hostingprovider/inline_tabular.html
As outlined in #134 ,  the current admin experience _isn't great_ when people submit lots of IP ranges to be updated, as there is no bulk edit option for staff when reviewing them.
This PR introduces a new bulk action, as as well as introducing tests and some custom templates for linking to a bulk edit view of IP ranges from a hosting provider. 
The idea here is that if you have lots of IP ranges to accept for a given provider, you can do them in bulk, instead of needing to reload the page each time for every IP address. Because some providers add ip-ranges in groups of 10-20 at a time this is helpful, and saves 10-20 page views for the poor admin.
- custom template for inlines (inline tabular)
- adding extra context for templates
- using ngettext for flash messages (singular and plural) …
=> Add bulk approval for Green IP ranges in the admin

apps/greencheck/viewsets.py
Re:  Issue #170
Appears that there was a mismatch between the key get and key delete.
=> Match cache key to invalidate stale data

Pipfile, Pipfile.lock, apps/theme/templatetags/admin_helpers.py, apps/theme/test_admin_helpers.py
We no longer try to look up a non existent domain, causing an unfortunate 500 error.
This also incorporates pytest-mock into our libraries, for future mocking.
=> Fix the bug in `link_to_ripe_stat` template tag

ansible/deploy.yml
Previously we didn't need this, as we didn't really upload any files
from users.
This adds the symlink so access to uploaded files persists between deploys (!)
=> Add the missing symlink for media uploads

apps/accounts/admin.py, apps/accounts/tests/test_admin.py, apps/theme/templatetags/admin_helpers.py, conftest.py
This is a fix for #181 - previously we were not checking if a class was in an array before removing it, which caused a crash when visiting the new hosting provider page.
=> Add test for visiting admin page as logged in user

Pipfile, Pipfile.lock, apps/accounts/models/hosting.py, apps/greencheck/serializers.py, apps/greencheck/tests/test_api_greendomain.py, apps/greencheck/tests/test_serializers.py, greenweb/settings/common.py
This PR introduces a new property in the JSON payload in the greencheck API, so when checking a domain, you can see the underlying evidence that we have access to for any green claims made by the hosting organisation, and that they have submitted into the public domain.
=> Add extended api response with supporting evidence

apps/greencheck/admin.py, apps/greencheck/tests/test_admin.py
This PR:
- introduces filters so that non-admin users only see their own approval requests in the django admin
- introduces a check on the bulk view so that only admins can see the options for bulk actions
=> Tighten roles in django admin for bulk actions and seeing approval requests

Pipfile, Pipfile.lock, apps/accounts/models/hosting.py, apps/greencheck/carbon_txt.py, apps/greencheck/choices.py, apps/greencheck/domain_check.py, apps/greencheck/management/commands/import_from_carbon_txt_url.py, apps/greencheck/models/checks.py, apps/greencheck/tests/carbon-txt-test.toml, apps/greencheck/tests/management/test_import_carbon_txt.py, apps/greencheck/tests/test_carbon_txt.py
This PR introduces the first parser and importer for carbon.txt.
More specifically, this PR introduces:
- **A CarbonTxt parsing and importing class** - it fetches a carbon.txt file at a given URL, written in TOML, and then converts the entities into the corresponding domain objects inside this codebase - namely "providers" and "supporting documentary evidence" for any green claims. This lets us expose this information in lookups against our existing greencheck API.
- **A django managemeent command** to import information from a given URL. This largely uses the importer above, and should be something that can be run idempotently against a domain, for cronjobs the like.
- **Updates to the domain checker**, to account for the existing of information provided via carbon.txt rather than using …
=> Introduce checking via carbon.txt

apps/greencheck/carbon_txt.py, apps/greencheck/tests/carbon-txt-test.toml, apps/greencheck/tests/test_carbon_txt.py
This adds alias support for importing with carbon.txt, allowing for aliases like `www.domainname.com` or `domain-name.com`, as alternatives to `domainname.com`.
=> Add aliases for carbon.txt importer

.gitpod.yml, scripts/test-rabbitmq.connection.py
This PR sets up the environment for using RabbitMQ and Redis as 'black box' external services running on the normal exposed ports, by using docker, rather than installing them as part of this development image.
This should make it easier to run the tests in a development environment without needing to know too much about the internals of either service.
=> Add rabbit and redis as docker containers for gitpod

.github/workflows/run-cloud-imports.py, .github/workflows/run-cloud-imports.yml, ansible/cloud-ip-range-import.yml
This PR adds a cronjob to run the AWS import on a daily basis.
It does this by starting an ansible run from inside a github action signs into the main box application server we have running in hetzner and runs the management command `pipenv run ./manage.py update_aws_ip_ranges`.
The ansible job allows us to add further imports for other cloud providers where we can point to evidence, like Microsoft, Google and so on.
Ideally we'd be able to run this without needing to have the ansible step - so we just have a github action, rather than a github action that calls an ansible playbook.
But in the short run, it at least allows us to run the ansible part in manually to test it out, rather than be reliant on the slow debugging process of using a github action.
If we wanted to run this entirely …
=> Add cloud import cronjob

apps/accounts/admin.py, apps/accounts/tests/test_admin.py
This PR changes the behaviour of the django admin, to filter out archived providers in our the admin views.
As much as possible, we don't delete old hosting providers, but we _do_ archive them.
This has an unfortunate side effect of showing archived providers in our provider list in admin views, which is confusing - you need to look for an "archived" checkbox as well as checking for the "show on site" checkbox.
This updates the listing to only ever show non-archived providers in the normal admin view.
If need be, there is still an override available - you can add `?archived=True` as a GET param in an url. This is helpful if you accidentally mark a provider as archived, and need to find it again.
```
https://admin.thegreenwebfoundation.org/admin/accounts/hostingprovider/ …
```
=> Hide archived providers by default in admin views

.gitpod.yml
This stops the notifications showing up each time when redis, postgres and rabbit are running.
=> Make port announcements quieter

greenweb/settings/common.py
This PR introduces a config change to support the massive form submissions that are made in the django admin by some hosting providers, and resolve issue #224.
More specifically, this switches from us using what I thought was a massive number for the total fields that we couldn't ever reach, to not trying to check _at all_, as it turned out that some form submissions far exceeded the limit I had before.
In the long run, we'd have a wizard-style multipart form, or API, but until then this at least makes submissions work again.
I wasn't sure if this should have a test, it's changing a config setting, and the code in the django framework doing the checking is here, which is already well tested. Here's the implementation code
https://github.com/django/django/blob/main/django/http/multipartpars …
=> Update the settings to no longer check for maximum field number size - resolves #224

apps/greencheck/api/legacy_views.py, apps/greencheck/domain_check.py, apps/greencheck/models/checks.py
This PR makes the multi-checks do a tiered lookup on multi checks.
This should address a bug where a result showed as green with a single check, but the same result would not show as green in mulit-checks
=> Update multichecks to try a tiered lookup

apps/accounts/admin.py, apps/accounts/models/hosting.py, apps/accounts/models/user.py, apps/accounts/templates/emails/provider-awaiting-review.html, apps/accounts/templates/emails/provider-awaiting-review.txt, apps/accounts/tests/test_admin.py, conftest.py
This PR introduces a few new changes
- **new notification emails for admins** - we send different emails now, and listen for more than just an IP / ASN approval request
- **updated flagging mechanism**  - we add a flag to the user that is visible in the admin, allowing us to see providers that need review
- **updated change detection mechanism** - we use the formset change detection APIs, to listen to changes made by non-admins that are made to the hosting provider, as all as any of the related items they have
=> Update flag and notify admin feature

templates/swagger-ui.html
This should resolve #290, where a reference to a now removed file was causing an embarassing crash.
=> Remove reference to removed polyfill

apps/greencheck/api/legacy_views.py, apps/greencheck/tests/test_legacy_v2_api.py
Closes https://github.com/thegreenwebfoundation/admin-portal/issues/266.
The root cause of the bug seems to be `NULL` value comparison in SQL. The field lookup `partner__in=[1, 2, 3]` [in Django translates to](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#in) the SQL query: `SELECT ... WHERE partner IN (1, 2, 3);`. This is problematic because in SQL NULL values are not comparable:
```
> SELECT 1 WHERE NULL IN ("", NULL);
Empty set (0.00 sec)
```
The QuerySet lookup was changed to [`isnull`](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#isnull), which is handled like this in SQL:
```
> SELECT 1 WHERE NULL IS NULL;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```
I also fixed the test, it failed to catch this bug before because the data that was used for …
=> Sort providers by partners first, then alphabetically by name

.gitpod.yml
This PR introduces the use of pre-installed VS code extensions, so we automatically can benefit from:
- using black for formatting by default
- flake8 for catching common linting issues, rather than needing to bring them up in code review
- isort for easier to read module import orders
More below:
https://www.gitpod.io/docs/ides-and-editors/vscode-extensions
=> Add extensions for python development in gitpod

apps/greencheck/admin.py, apps/greencheck/forms.py, apps/greencheck/models/checks.py, apps/greencheck/tests/test_models.py
Closes https://github.com/thegreenwebfoundation/admin-portal/issues/292.
Scope of changes:
- Added model-level validation to `GreencheckIp` and `GreencheckIpApprove` models. Now newly submitted IP ranges (via `ModelForm`s that are using those models) will be automatically validated - tested manually in Django admin
- Added a test for the validation logic
- Changed the order of definition of fields in `GreencheckIp` and `GreencheckIpApprove` models. Thanks to this small change `IP start` is now displayed before `IP end` in the admin panel (hopefully making it more intuitive to input the data)
- Fixed some typos and formatting (in the files that I worked on)
=> Validate IP ranges

greenweb/settings/common.py, one_day_to_parquet.py
This PR adds some checks for the stats worker tasks to avoid proceeding when we have no data to upload or convert to parquet files, as well as extending the default timeout for long queries. 
Some queries were taking longer than 10 minutes so this stops them erroring out.
=> Add tweaks for dramatiq workers

apps/accounts/admin.py, apps/accounts/tests/test_admin.py, templates/admin/accounts/datacenter/fieldset.html
This PR changes the how we present the data centre page to only allow green web staff to associate providers with a given datacentre.
Previously we allowed hosting providers to declare this connection, which we would validate afterwards, but this switches it around so that we only update information once we have had a request to update it, and approved the change.
**What normal, non staff users see**
With this PR merged in, regular users see something like this example provider. You can see hosting providers associated with the datacentre, but you can not change them. We link to a support form to request changes. Very few changes are made to datacentres each month (I only saw 6 in Sept) so this doesn't sound like it would create a massive support burden.
**What green web staff see**
Our …
=> Update how we show datacentres - fixes #317

greenweb/settings/production.py
Hi @tortila I had a quick look at adding "spans and traces" support into this app, and it turns out to be a 1-2 line change.
This PR introduces the change, and documentation in the config file, but until an environment variable is set, there will be no changes to existing functionality, and no trace information will be sent.
I figured adding this would mean that we can:
1. catch behaviour in staging as we develop the new work
2. check out any per issues with prod traffic,  assuming we sample sensibly, or even split how traffic going to admin.TGWF differently is dealt with versus api.TGWF (api receives literally 1000x the traffic).
C
=> Add sentry tracing for investigating slow requests

apps/greencheck/models/checks.py
This fixes #325 to ensure the correct value is returned as a fallback for global average generation from fossil fuel.
=> Fix global avg fossil generation value

templates/partials/docs_banner.html, templates/swagger-ui.html
This PR adds a simple banner to the top of the `/api-docs/` page which links out to the new developer documentation website.
This gives exposure to the new documentation site, which provides more user-friendly API guidance. Although the new site currently only covers two APIs (Greencheck and IP to CO2), it is expected that will expand to cover all the major Green Web Foundation APIs.
=> Link to dev docs site from API docs

.github/workflows/run-deploy-staging.yml, Pipfile, Pipfile.lock, apps/greencheck/directory_urls.py, apps/greencheck/views.py, apps/theme/templates/greencheck/directory_index.html, greenweb/settings/common.py, greenweb/urls.py
This is a work in progress demo of setting up our filtering.
If you visit `/directory`, you'll see a filterable view, allowing you to filter by country, service provided and provider name.
This work is behind a the `directory_listing` feature flag.
I've done almost no work to try to speed up queries, and as as result it's not fast.
I think this is because for every provider on a page, we do more queries to fetch the tags and the names, when we could get them just one with `prefetch_related`. It's not a thing I'm so familiar  with, so I'd appreciate someone pairing with me to figure it out.
=> First pass at directory filtering

Pipfile, Pipfile.lock, apps/accounts/filters.py, greenweb/settings/common.py
This PR adds support for using multiple filters when filtering hosting providers up to a maximum of 4 simultaneous tags.
Previously our filter view looked like this:
Now we have an option to progressive filter by more tags, up to a maximum of four tags at the same time. 
This is an AND query, not an OR query, so it will only match items that have all the active tags. 
When more than four filters are in active use a warning message is shown and advises users how to reactivate the filtering.
This code is not beautiful, but it seems to work.
=> Support multiple active filters. Fixes #348

greenweb/settings/production.py
Any domain ending with greenweb.org and thegreenwebfoundation.org, both of which we control can be used. This allows for creating easy staging domains
=> Add more permissive allowlist in allowed hosts

apps/accounts/admin.py, apps/accounts/filters.py
This PR introduces two changes for the hosting provider view.
1. We show the staff labels that have been applied to existing providers. This should save needing to click through each time to see what labels have already been applied. Only green web admin see these labels - they're not intended to be visible for end users, because if we did we'd need to make sure every label was externally documented.
2. The partner filtering now filters by the status of the provider, rather than simply offering a boolean True/False option. It turned out that no partners are labeled as `True` anyway, and this now allows us to see the previous gold partners, the previous dev partners and so on.
As before this is visible on the staging site.
=> Update admin view to show staff labels for admins, and allow filtering by partner status

apps/theme/static_src/package-lock.json
This PR updates a number of the front end dependencies that tailwind has, and should allow us to close a number of automatic PRs created by dependabot, resulting in a much tidier repo.
=> Update front end dependencies

.gitpod.yml, apps/theme/static_src/tailwind.config.js
This PR fixes #358  where misconfiguration of tailwind meant that changes to templates were not being picked up.
This meant that the handy tailwind typography classes where not being generated when needed.
This also makes the gitpod.yml create a new terminal for running tailwind in watch mode.
=> Fix #358 - tailwind not picking up typography plugins

apps/theme/templates/style-guide.html, apps/theme/tests.py, apps/theme/views.py, greenweb/urls.py
This PR adds a new style guide template.
This doesn't do anything clever to tell tailwind to exclude it when building form templates,  so as we build out this guide we will likely need make sure our build steps don't automatically include the classes for every component  used of they're not actually used in our app.
Visit `/style-guide`, to serve the style guide template file.
This combined with the ability to create services using the taggit app in the django admin looks like it would be what's needed to create at least one service for completing the styling on the multipart form. 
Visit `admin/taggit/tag` as the superuser in development to be able to create the services - you will need to add the name and the 'slug'.
=> Add simple style guide view and template

Pipfile, Pipfile.lock, apps/greencheck/tests/views/test_basic_auth.py, greenweb/settings/common.py, greenweb/settings/staging.py
This PR adds Basic auth checking for use in staging environments.
It introduces three new environment variables with what should be helpful defaults that we can override if need be:
```
BASICAUTH_DISABLE=(bool, True),
BASICAUTH_USER=(str, "staging_user"),
BASICAUTH_PASSWORD=(str, "strong_password"),
```
We also have a few basic tests to exercise this code. 
Why have this?
From painful experience when debugging issues, it's really helpful to sanity check why changes might not be reflecting on a site, and if a link to a staging site is shared by accident to external users, it saves on support questions.
There is an argument about being able to control who sees what we're doing but given we're an open source codebase, that's much less of an issue.
=> Staging basic auth

apps/accounts/forms.py, apps/accounts/models/provider_request.py, apps/accounts/templates/provider_registration/network_footprint.html, apps/accounts/tests/test_form.py
Scope of changes:
- changed the type of the field for IP addresses in the form to [`GenericIPAddressField`](https://docs.djangoproject.com/en/4.1/ref/forms/fields/#genericipaddressfield) for both: IP start and end. This is a built in type that provides the validation for IPv4 and IPv6 addresses,
- added a small change in the `ProviderRequestIPRange.clean` so that the validation provided by `GenericIPAddressField` kicks in properly + documented the unexpected behavior,
- added form tests that cover edge cases,
- minor changes in the wording on the IP ranges form ("delete" button is tied to a single IP range, not multiple)
=> Validate IP addresses in the registration form correctly

apps/accounts/forms.py, apps/accounts/templates/provider_registration/partials/_preview.html, apps/accounts/templates/provider_registration/preview.html, apps/accounts/tests/test_provider_request.py, apps/accounts/views.py, docs/index.md, docs/veirification-request.md
**Scope of the changes:**
- the last step in the wizard (PREVIEW step) renders all cleaned data from the previous steps.
- new template for the PREVIEW step
**Out of scope** for now (will be delivered in the upcoming PRs):
- printing of the summary to a file
- "Edit" buttons for each section with hyperlinks to the corresponding wizard step
**Implementation details:**
- new `PreviewForm` that has no fields or logic and only serves as a placeholder in order to render an additional template at the end of the wizard steps,
- cleaned data from all previous steps is injected to the template context as unbound forms,
- the preview template renders each form in a separate section on the page.
I added comments in the code to describe all the weird bits of this implementation and I hope this will …
=> Preview of the verification request

apps/greencheck/views.py
See the linked Trello card below:
https://trello.com/c/tZGF3Tpe/13-remove-name-contains-field-from-search-filters
=> Remove name search field for directory filter

apps/greencheck/management/commands/fetch_from_bucket.py
This PR introduces a command to fetch files from buckets in object storage, where we store backups, exports of data and so on.
Because adapting the aws cli command is a bit involved when you're not using Amazon, this makes it easier to fetch files in our workflow.
You run it like so:
```
./manage.py fetch_from_bucket BUCKET_NAME PATH_TO_FILE LOCAL_FILENAME
```
Where `BUCKET_NAME` is the object storage you want to access, `PATH_TO_FILE` is the key for the given file in object storage, and `LOCAL_FILENAME` is the name of the file to save something to.
Under the hood, this uses the boto3 download_file command, so it uses multiple threads to speed up transferring big files
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html?highlight=s3transfer#boto3.s3.tra …
=> Create management task for fetching files from object storage buckets

apps/accounts/templates/provider_registration/consent.html, apps/theme/static_src/src/css/custom/forms-custom.css, apps/theme/static_src/src/css/custom/forms.css
To override how a table is styled in the consent page, we overridde the `content` block.
You can see us doing this already in the `consent` page, where we add this extra stuff.
```
{% block header_section %}
<section class="prose mt-10">
<h1>One last thing...</h1>
<p>We want to check you consent to us storing and processing the data you provided in different ways.</p>
</section>
{% endblock %}
```
This inserts it into the  `header_section`  block that is otherwise empty in the base_form, which normally looks like this:
```
{% block header_section %}
{% endblock %}
```
In this case because the content block contains the `header_section` section anyway, we put it _inside_ the content block
=> show example of overriding template

apps/accounts/forms.py
Sets `label_suffix=""` to both fields of the `ConsentForm`, which removes the default colon (`:`) character from the label. 
See the docs here: https://docs.djangoproject.com/en/4.1/ref/forms/api/#django.forms.Form.label_suffix
Now the consent form looks like this (notice lack of `:` at the end of the text after the checkbox)
This was prompted by @hanopcan question in https://trello.com/c/MpxIk6d8/89-style-consent-page#comment-63d3f66c43f8c55b495f6f9f and was very easy to implement.
=> Remove label suffix in the consent form

apps/accounts/models/provider_request.py
Small change to display the URL or file name for each evidence on the detail view of the `ProviderRequest` object.
=> Display URL/file name on the detail view of ProviderRequest

apps/accounts/templates/emails/verification-request-notify.html, apps/accounts/templates/emails/verification-request-notify.txt, apps/accounts/tests/test_provider_request.py, apps/accounts/views.py
This PR introduces the logic to send an email to:
1. our internal support address
2. the user who submitted the form
The email message contains a link to the submission for reference along with a helpful message.
=> Send email notification to support staff and user when submitting a form

apps/accounts/templates/provider_request/detail.html, apps/accounts/views.py, apps/theme/static_src/src/css/base.css
On successful submission of the verification request, we display a success notification on top of the page (detail view of the request). Here's what it looks like:
Please feel free to give suggestions on either styling or the copy.
=> Add success notification on submitted verification request

apps/accounts/admin_site.py, apps/accounts/templates/provider_request/list.html, apps/accounts/urls.py, apps/accounts/views.py
This is matched to the trello card below:
https://trello.com/c/GVakUTC9/7-verification-request-self-serviced-user-creation
This PR adds a few main changes:
1. It changes the default styled sign urls, so we now have `/accounts/login/` to log in, and `/accounts/signup/` to sign up / register.
2. Changes the default place you end up when signing in to be the verification list, with the new branding
I added two smaller changes after adding this, as I realised once you had signed in, it wasn't obvious how to move between the two worlds of the old admin (where existing users might need to update info on an existing provider), and the new one (where if you are on the old admin, you can't easily access the new verification screen).
These are: 
1. It make the verification requests accessible from …
=> Update path, add verification request in admin

apps/accounts/forms.py, apps/accounts/templates/provider_registration/evidence.html
This PR changes the copy to support cases where a provider will share evidence for a company in their supply chain, to demonstrate that the emissions from the energy have been accounted for properly, but where their own company is not named.
If you are hosting provider, and you are paying for colocation services from another datacentre operator, the evidence might be linked to the datacentre (like a green energy tariff), not yourself.
=> Add change to copy for providers sharing evidence that doesn't name them specifically

apps/accounts/admin.py
This was requested by Justine at the demo session today. In case we need to reach out for more information to the user who submitted a verification request, it's useful to have their contact info one click away from the admin change view. The readonly field is rendered as a hyperlink to the User admin change view, that contains the email address.
Before:
After:
=> Hyperlink to user page from the ProviderRequest admin

apps/accounts/admin_site.py, apps/accounts/templates/try_out.html, apps/accounts/tests/sample.rdap.output.json, apps/accounts/tests/test_admin.py, apps/greencheck/domain_check.py
This PR:
1. converts our detailed greencheck feature to use GET requests, so links to a specific check can be shared easily
2. refactors the the code so more is happening in the view, rather than the form, and we have more tests
3. renames the url to be more consistent with other urls, and more descrptive - so an extended greencheck is at `extended-greencheck`, rather than just `try-out`.
=> Refactor domain check and work with GET requests

apps/accounts/admin_site.py, apps/accounts/models/hosting.py, apps/accounts/templates/carbon_txt_preview.html, apps/greencheck/admin.py, apps/greencheck/carbon_txt.py, apps/greencheck/tests/carbon-txt-refined.toml, apps/greencheck/tests/carbon-txt-test.toml, apps/greencheck/tests/test_carbon_txt.py
This PR adds a some sample scaffolding for building a parser for carbon.txt files, so we are able to:
1. fetch a carbon.txt file from a given url
2. parse the TOML, raising exceptions if parsing fails
3. replace the linked providers with info we have in our database in the results
This is very WIP, and not really intended for public consumption yet, but should allow us to start checking and validating real files in the wild, while we start working on some outreach with other partners
=> First pass at making a carbon.txt parser

apps/greencheck/admin.py, apps/greencheck/models/checks.py
This PR introduces the ability for staff to lookup AS and IP ranges, and filter by a number of criteria including:
- hosting provider
- whether the provider is archived or not
- active / inactive state
This also provides a search feature for quickly finding the IPs or ASNs that should be allocated to a given provider
=> Add ways for staff to navigate IP and AS ranges

apps/accounts/forms.py, apps/accounts/templates/provider_registration/evidence.html, apps/accounts/templates/provider_registration/locations.html, apps/accounts/templates/provider_registration/network_footprint.html, apps/accounts/tests/test_form.py, apps/accounts/tests/test_provider_request.py
This PR introduces checks at the formset level, to avoid cases where someone is able to work through the wizard form without adding location data or supporting evidence.
Previously, if we didn't have this check, using the django formset factory API, a user could sail through without adding the necessary info.
If we _did_ have the check though, it turned out that the formset errors we not surfaced onto the page, so users would be stuck not understanding why the step could not progress.
This PR introduces logic to add our usual defaults, but also to change the `errors` method logic on our multiform(s), so we display the correct error for the template to render.
Finally, this PR tweaks the error message so it's easier to understand in the template (we change the word 'form' to 'location')
=> Add checks for empty formsets in form wizard

apps/accounts/admin_site.py, apps/accounts/templates/carbon_txt_preview.html, apps/greencheck/carbon_txt.py, apps/greencheck/tests/test_carbon_txt.py
This PR adds support for debugging carbontxt files.
When you add just an url, the parser preview now follows header `Via` information, as well as looking for DNS TXT records on a given domain.
This makes it possible to see where a chain of lookups will follow when testing your own carbon.txt file at a given url, as well as test which domains already ready return information for a given url.
=> Add support for Via Header and DNS lookups in carbontxt preview

apps/accounts/admin_site.py, apps/accounts/templates/carbon_txt_preview.html, apps/greencheck/carbon_txt.py, apps/greencheck/serializers.py, apps/greencheck/tests/test_carbon_txt.py
Some earlier work on PR #441 had the issue number 338 in the branch name when it should have been 438.
This PR supercedes the earlier branch, as it should have a the correct branch name for future reference.
https://github.com/thegreenwebfoundation/admin-portal/pull/441
=> Essentially the same PR as #441, but with a more sensible branch name

apps/accounts/views.py
This is using a built-in validation mechanism from the library `django_registration`: https://django-registration.readthedocs.io/en/3.3/forms.html#django_registration.forms.RegistrationFormUniqueEmail
Result:
=> Do not allow registering a new account if email exists in db

apps/accounts/forms.py, apps/accounts/tests/test_form.py
Scope:
- overwrite `non_form_errors` method of the formset to replace the error message when too few forms were submitted
- add a test
=> Change error message when no green evidence submitted

apps/accounts/templates/base.html
Scope:
- move the `base.html` template to a new location (FYI @hanopcan, we discussed it briefly)
- change the hyperlink on the top-left logo to link to the provider portal landing page (`/requests`)
=> Logo on provider portal links to the portal landing page

apps/accounts/views.py
Scope:
- monkey-patch the constant `django_registration.validators.DUPLICATE_EMAIL` to customize the error message when a duplicate email address is entered on the registration form
Based on the feedback in this card: https://trello.com/c/LksNap11/125-handle-new-user-submissions-to-avoid-double-accounts
=> Change error message on duplicate email validation

apps/accounts/templates/emails/verification_request_approved.html, apps/accounts/templates/emails/verification_request_approved.txt
This PR comments out references to listing public evidence in our directory.
We intend to have this in the new directory, but in the directory profile views that display the evidence are coming later.
In the meantime, the old directory currently does not list supporting evidence that is uploaded , so it's best to not mention this until it's visible.
=> Hide the reference to directory evidence for now in email confirmations

apps/accounts/forms.py, apps/accounts/templates/provider_registration/locations.html, apps/accounts/templates/provider_registration/partials/_preview.html, apps/accounts/templates/provider_registration/preview.html, greenweb/settings/common.py
Scope:
- minor fixes to help text on the verification request form
- expanding country codes to names on the preview page, by utilizing `django_countries` template tag
- custom logic (expanding country codes to names, expanding service slugs to service list) on the preview page is now done based on the field label -> this will ensure that random user input on unrelated fields is not transformed
=> Verification request form: fixes after 1st round of user testing

apps/greencheck/api/legacy_views.py, apps/greencheck/tests/test_legacy_directory.py
This PR is intended to solve issue  #459, where we were seeing a lot of invalid API requests causing 500 errors in Sentry.
This was triggered when people use the old directory to look up what information we have about a given provider, and it looks like someone starting hitting that API pretty hard - triggering hundreds of exceptions in the last few days, from the same client.
With this merged in, we instead serve a 406 response, making it clear to consumers how this endpoint is intended to be used.
https://github.com/thegreenwebfoundation/admin-portal/issues/459
This also tidies up the code with Ruff, removing unused variables and so on
=> Catch API exception and serve helpful error response

apps/accounts/templates/provider_portal/home.html
Fix a hyperlink name and URL on the provider portal page, addressing feedback from Justine.
=> Replace 'how to get registered' -> 'how to get verified'

apps/accounts/admin.py
This PR introduces a change where we make sure we show the correct services model on the verification request admin screen.
Previously, we were defaulting to showing basic 'Tag' model instances, which we do not want, as we have a dedicated Service model now.
=> Show correct services in verification request admin

apps/accounts/tests/test_provider_request.py, apps/accounts/views.py
As requested in feedback when adding the the bcc to a mail-to-board listing in trello
=> Add provider name to email submission

apps/accounts/templates/base.html, apps/accounts/templates/provider_portal/before_starting.html, apps/accounts/templates/provider_portal/home.html, apps/accounts/templates/provider_portal/request_detail.html, apps/accounts/templates/provider_registration/preview.html, apps/accounts/urls.py, apps/accounts/views.py
This addresses a few smallish requests as documented here: https://trello.com/c/jXbmbWuf/177-add-copy-tweaks-from-first-round-of-usability-observations
Specifically:
1. It adds the "provider portal" subbrand to the header
2. It inserts a new page between the provider home and start of verification form to set expectations about what info to prepare and what to expect
3. It retitles the preview page
4. It amends the success message displayed on final summary page
5. I have moved the link to the old admin interface to a more intuititive position on the page and removed the title.
For step 2 please code review carefully. I set up a new URL path and pointed it to a new html template. No idea if I have done this in the best way but it's highly likely I won't have (stack overflow was involved, …
=> Hs copy tweaks

apps/accounts/admin.py
There are cases where we need to update datacentres still. This makes is possible for staff to update the location of a datacentres that are already associated with a given provider.
=> Support staff changing datacentre location

apps/accounts/models/provider_request.py, apps/accounts/tests/test_provider_request.py
This PR introduces support organisations that do not offer hosted services, when sending verification requests, as well as defaulting to showing providers in the directory by default after they have been approved by staff.
=> Update approval process to annotate providers and check for non-hosting orgs

docs/index.md, docs/users-permissions.md
Adds documentation to explain how we use the permission system + providing extra context about users and groups.
Note: this branch is based on `oz-object-level-permissions` because it documents the object-level permissions mechanism that is implemented there. Do not merge until https://github.com/thegreenwebfoundation/admin-portal/pull/481 is merged
=> Document users, groups and permissions

apps/accounts/tests/test_provider_portal.py, apps/accounts/views.py
Note: this branch is based on `oz-object-level-permissions`. Rebase on `master` before merging!
=> Sort verification requests and hosting providers alphabetically by name on the Provider Portal home page

apps/accounts/admin.py, apps/accounts/tests/test_admin.py
As a regular user, when I go to a hosting provider change view in the admin panel, I can see other users who can manage that provider. If I click on one of the usernames that is not mine, I'm getting redirected to the main admin page and I see a message: "User with ID XXX doesn't exist. Perhaps it was deleted?". The default message is somewhat confusing and indicates that the user could have been deleted. This is because for non-admin users we filter the queryset to only include their own object - which makes Django deduct that the user with given ID does not exist.
=> Make the error message clear when users are accessing another user admin page

Pipfile, Pipfile.lock, ansible/inventories/prod.yml
This should fix an issue with app2 (and now app4) not being able to pipenv install reliably on deploy. 
This appears to be related to the 2.2.x release of [mysqlclient](https://pypi.org/project/mysqlclient/) which has a new system dependency, `pkg-config`.
From the release notes
> What's Changed
> 
> **mysqlclient uses pkg-config since v2.2. You need to configure pkg-config, or manually set envvars.**  
> [READ the manual](https://github.com/PyMySQL/mysqlclient#install)
Source: [PyMySQL/mysqlclient: MySQL database connector for Python (with Python 3 support)](https://github.com/PyMySQL/mysqlclient/releases/tag/v2.2.0) by @github
I think `pkg-config` was installed on app1 ages back for something, but it is not included in the ansible setup scripts for new machines yet - this would explain …
=> Pin the version of mysql client

apps/accounts/tests/test_provider_request.py, apps/accounts/views.py
The detail view of verification requests - the page that is rendered when accessing the URL we send in confirmation emails, e.g. https://admin.thegreenwebfoundation.org/requests/35/, was only accessible by users who originally submitted the request. This is caused the link to return 404 when accessed by admins. With these changes, admins are able to access the detail view of all verification requests.
=> Make the detail view of verification request always accessible for admins

apps/greencheck/tests/test_directory.py, apps/greencheck/views.py, apps/theme/templates/greencheck/directory_index.html
This PR introduces our list of providers grouped by country, as outlined in the Trello card below:
https://trello.com/c/zfA4swmo/183-directory-output-list-of-providers-by-country
It also introduces a couple of simple tests.
The first is a sanity check that requests sent to `/directory` work.
The second is a check that when we have our list of providers we are ordering them by country name. We use django's built in [#regroup](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#regroup) template tag to reorder the providers in the template, because this makes it easier to understand what's going on when Han is working at the template layer, and because implementing out own regrouping logic seemed to replicate what django offers us already. 
The main consideration was that becuase …
=> Add regrouping of providers in directory

apps/greencheck/tests/test_directory.py, apps/theme/templates/greencheck/directory_index.html, apps/theme/templates/greencheck/partials/_directory_results.html, apps/theme/templates/greencheck/partials/_no_directory_results.html
This PR introduces a conditional so we show two different templates, depending on whether we have results coming back from our combination of filters in play for the directory.
**Note:** we probably want to revisit where we put all the templates in future, as we currently have three separate folders for them. This is not an urgent priority though.
=> Add conditionals for showing directory results

ansible/_add_system_dependencies.yml, ansible/_set_up_process_mgmt.yml, ansible/deploy.yml, ansible/inventories/prod.yml, ansible/inventories/staging.yml, ansible/provision_app.yml, ansible/scale_processes.yml, ansible/templates/supervisor.gunicorn.conf.j2, ansible/templates/supervisor.worker.conf.j2, docs/deployment.md
This PR updates our deploy scripts to reflect the use of the new app servers, along with a refactor to allow for updating how many gunicorn or dramatiq processes are working on each server without going through the full deploy process
=> Update server deployment and process management scripts

ansible/_set_up_directories.yml, ansible/deploy.yml, ansible/inventories/prod.yml, ansible/inventories/staging.yml, ansible/templates/dotenv.j2, ansible/templates/run_gunicorn.sh.j2, ansible/templates/supervisor.gunicorn.conf.j2, greenweb/settings/production.py
This PR allows us to set Sentry's tracing on our apps on a per machine basis, so we can get an idea of where performance bottlenecks lie. 
Previously we had api.TGWF and admin.TGWF running on the same server, but since expanding to more machines, this allows us to serve admin.TGWF (which receives like.. 1000x less traffic) with sentry tracing on the app3 server, where we could run the tracing without blowing through our quota, and api.TGWF on the other machines, where we do not.
This also supports sampling on the API servers, but because admin.TGWF still gets some API traffic, this is currently assumed to be less of a priority.
=> Add support for sentry tracing

Pipfile, Pipfile.lock
This resolves the issue we've seen in the django staff admin - previously we had the handy tag auto complete used by staff, OR the toggles for listing services a provider offers but not both.
=> Downgrade Django Autocomplete Light explaining why

.github/workflows/run-deploy-staging.yml, .github/workflows/run-deploy.yml, .github/workflows/run-tests.yml
This updates the underlying test runners we use, so we are no longer using an end of life version of node in them.
=> Update github actions to use newer runners

apps/greencheck/tests/test_api_logger.py
This PR adds two more tests for the API logger - we do not use the live server, instead favouring mocking the logger that exists on the middleware.
This has the advantage of running in CI for us, so we have some coverage. We retain the heavier tests using the `live_server` fixtures if we want to exercise more of the code when investigating issues.
=> Refactor tests and add two using our mocked logger

docs/deployment.md
This PR adds a few 'breadcrumbs' linking to our infra repo, and some relevant cards related to the recent changes we made when handling our migration to a new machine, and bringing more of our VMs under config management.
=> Add docs with links to other infra repos and relevant cards

apps/accounts/templates/provider_registration/network_footprint.html
Text change request from @fershad 
More details here: https://trello.com/c/JZVQsTSb/256-change-help-text-on-ip-range-part-of-verification-form
=> IP range text change

apps/accounts/forms.py, apps/accounts/models/provider_request.py, apps/accounts/tests/test_provider_request.py, apps/accounts/views.py
This PR picks up the earlier work in #522, to address the problems we saw when updating an existing provider using the form wizard.
The problem is detailed in that PR, but the short version is that some data in forms contained within django formsets were not making it through the form wizard, which means when updating a provider request, if there were forms in a formset that had no changes, they were being dropped.
This was a blocker as it meant that on approval, our provider would be updated with incomplete information.
This only seemed to happen when our wizard form contained formsets that contained forms with unchanged data, and after exploring various options, I arrived at the idea of introducing a mixin class for use in forms we use in the form wizard.
All it does is adapt form …
=> Add support for updating hosting providers when not all forms change in wizard

apps/accounts/models/hosting.py, apps/greencheck/models/stats.py
This removes the annoying  bunch of warnings we see when we run any management command with django:
```
WARNINGS:
accounts.DataCenterLocation: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
accounts.Datacenter: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
accounts.DatacenterCertificate: …
```
=> Create default primary key for django 3.2

apps/accounts/admin.py, templates/admin/accounts/hostingprovider/change_form.html
This PR introduces a fix in the admin where if a provider has more than 500 IP Ranges, it wasn't possible to save changes to that provider.
**What was going wrong and the fix I used**
Previously, when we havd more than 500 IPs presented on a provider, instead of showing a massive list of IP addresses to change, we should show a bit of HTML linking to a view of IP ranges scoped to a specific provider, which could be edited in isolation.
The problem was that under the hood, when you are on a provider change form and you see the various inlines for IPs, supporting evidence, ASNs and so on django represents these as a giant form.
Internally each inline has a few hidden inputs that django checks for when processing data, and it raises errors on that specific formset in the templates.
Also, …
=> Fix django admin edit bug when a provider has lots of IPs

apps/accounts/admin.py
This is used internally, for handing updates, but should probably not be exposed in the django admin like this, as it can lead to unintended destructive data updates to an existing provider.
=> Remove "provider" from admin view for verification request approvals

Pipfile, Pipfile.lock
This is a PR to merge in Marimo, a software library that makes carrying out anaylsis of greenweb data using the ORM made available by Django.
We've use it like so in development, when working with a working database connection:
```
pipenv run marimo edit ./scripts/path-to-analysis-file.py
```
The scripts would be kept in a file that is listed in `.gitignore`, or potentially a git submodule.
=> WIP: Add Marimo as a dependency

ansible/setup_cronjobs.yml, ansible/templates/import_ips_for_large_providers.sh.j2, docs/recurring-tasks.md
This PR adds sets up a cronjob using Ansible for our weekly imports, replacing any manually created cronjobs.
The output is logged to files which are then shipped to our centralised logging system.
=> Add cronjob for weekly imports and supporting files

ansible/setup_cronjobs.yml, ansible/templates/export_green_domains.sh.j2, ansible/templates/import_ips_for_large_providers.sh.j2, docs/recurring-tasks.md
This re-introduces via Ansible the daily green domains snapshot we had before.
We run this on the app1 box, because it has more memory than the other app servers (8gb RAM vs 4gb RAM).
=> Add cronjob via ansible for daily green domain exports

.github/workflows/run-deploy-staging.yml, .github/workflows/run-deploy.yml, ansible/templates/dotenv.j2, apps/accounts/templates/base.html, apps/theme/context_processors/sentry.py, greenweb/settings/common.py, greenweb/settings/production.py
This PR adds some Sentry error monitoring code to the frontend of the platform so that we can better placed to understand and investigate frontend errors being reported by users.
Uses code from:
https://docs.sentry.io/platforms/javascript/
https://docs.sentry.io/platforms/javascript/troubleshooting/#capturing-resource-404s
Currently, the main purpose of this implementation is to capture information about a long running, sporadic CSS loading issue that has been experienced on the frontend.
=> Add sentry to portal frontend

ansible/templates/supervisor.gunicorn.conf.j2, ansible/templates/supervisor.worker.conf.j2, docs/deployment.md, gunicorn.conf.py
This PR updates some of the internal config to make it much easier to track the logs from our application, and aggregate them in our centralised logging server.
More specifically, it creates files like so, that are easy to pick up and read with our log forwarders
**For the web servers**
Logs go to the following files.
/var/log/web_prod_00.log
/var/log/web_prod_00.error.log
We rely on gunicorn's native handling of multiple processes rather than supervisor' support.
This means that supervisor watches one main gunicorn process, which forks other workers, and all _their_ logs are aggregated and fed into the following two files.
**For the background worker processes**
Logs for the workers using dramatiq go to the following files:
/var/log/worker_00.log
/var/log/worker_00.error.log
Just like …
=> Add updated supervisor config files for clearer logging

apps/accounts/views.py, apps/greencheck/api/legacy_views.py, apps/greencheck/carbon_txt.py, apps/greencheck/domain_check.py, apps/greencheck/tests/test_importer_csv.py
This PR adds validation of values that might not be domains to our legacy multicheck at the following endpoint.
```
/v2/greencheckmulti/{url_list}
```
Previously we didn't validate each entry, so this now filters out values which are not domains
=> Add check for valid domains on the multi check endpoint

apps/accounts/models/hosting.py, apps/accounts/models/test_models.py, apps/greencheck/carbon_txt.py, apps/greencheck/tests/test_carbon_txt.py
This PR introduces a few changes to how carbon.txt lookup delegation works, to make it clearer how domain hashes work when verifying that someone is able to link a new domain to a verified provider.
A quick summary
- **Add a `domain_hash_for_domain` method on a hosting provider** - this uses the shared secret added to the provider to generate a domain hash
- **Update the ` _check_domain_hash_against_provider` method on the carbontxt parser** - this now uses the `domain_hash_for_domain` method, and has a different method signature that emphasises the role the provider plays
- **Update `_check_for_carbon_txt_via_header` and ` _check_for_carbon_txt_dns_record`** methods - the method signatures are fleshed out, and the flow should be clearer now
- **Add tests to demonstrate the new domain …
=> Update how domain hash checks work

greenweb/settings/common.py
See trello card linked below:
https://trello.com/c/nuq9UpR1/1080-support-request-from-nuggan85
this adds the change outlined below in the docs for the django-mysql library we use to connect to MariaDB
https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4
=> Ensure ut8mb4 connection to MariaDB

apps/greencheck/domain_check.py, apps/greencheck/tests/test_domain_checker.py
This PR is intended to resolve #573 , which came up when we realised that domain lookups that resolve to an ipv6 address were not working properly.
It covers both cases, and lays the path for a updating this to check ALL ip addresses a domain might resolve to in future, not just the first one. 
We don't immediately moved to checking every domain, as I'm not sure of the performance implications, and there are a few places that expect just one ip address to be returned - we'd need to make quite a few changes elsewhere.
=> Fix ipv6 support in domain lookups

apps/accounts/admin.py, apps/accounts/tests/test_provider_request.py, apps/accounts/views.py
This PR introduces use of the django log entry feature to provide a more accessible audit log when staff or users are working with verification requests.
=> Audit logs for creation and updates to verification requests

.dockerignore, .env.docker.sample, .gitpod.yml, Dockerfile, compose.yaml, docs/deployment.md, docs/installation.md, docs/working-with-docker.md, greenweb/settings/common.py, makefile, scripts/build_containers.sh, scripts/install_package.sh, scripts/test-rabbitmq.connection.py
This PR introduces docker support in our project, so that we can run the various parts in a docker and docker compose.
While we don't yet use docker in production to run the platform, this at least allows us to do so, and crucially allows us to run the system in the Green Metrics Tool, to give us some indicative numbers for resource usage (energy, carbon etc.) for various parts.
=> Add docker support for working with Green Metrics Tool

.github/workflows/run-tests.yml
Hey @mrchrisadams ,
here is the promised Eco-CI integration sample PR!
What I did:
- Integrate Eco-CI initially and initalized it also with CarbonDB. Your runs will then not only show up here in the Eco-CI view, but also in Carbon DB
- Eco-CI View: 
- CarbonDB view: https://metrics.green-coding.io/carbondb-lists.html?company_uuid=7f1d34f0-7666-4378-8d8f-d37cced7ccb0
I have assinged the company UUID `7f1d34f0-7666-4378-8d8f-d37cced7ccb0` for your company. Note that you can use any ID. You should just double check that nobody else is using it.
- I integrated a measurement step after every step in the workflow. This way you get a nice granular view of all steps and how they relate in consumption
- I integrated `send-data: true`. This will send data here: …
=> Eco-CI integration

apps/accounts/static/accounts/js/compiled.select2.js, templates/admin/change_form.html
This PR introduces two things:
1. an override of the hosting provider change_form, to allow us direct control over which scripts are loaded by the page, and in what order
2. a concatenated javascript file, created to overcome the incredibly frustrating clash of different versions of jQuery, select2 and other scripts being loaded onto the page, that led to the autocomplete tag widget failing to load properly since we upgraded Django.
There is no magic for the concatenated file, and I am not using any bundling tools - it's literally a file where I have pasted the files in the order we need them to load, and will need to be updated when we make any further changes to this hosting provider admin page.
We're in the process of removing access to these django admin pages to non-staff users - so …
=> Fix the django autocomplete / select2 upgrade bug

apps/accounts/views.py
This PR pulls in what I think is the final piece of info for missing from reverification if we have a previously filled out verification request.
Before when a provider had filled in a reason for why they were not submitting IP ranges or AS numbers (for examaple if they were going to share an CSV file full of IP ranges etc), this info was not prepopulated with the data we had.
This was because the the `NetworkFootprintForm` form in use was really a _multi-model form_, comprised of three different kinds of forms, and to populate it correctly, we needed to match each a form object with a corresponding dictionary data structure.
In the final case we were just passing a value, rather than passing a dictionary containing the values we needed.
Phew!
=> Add the missing info for the network wizard

apps/accounts/templates/provider_portal/home.html
This PR adds a flag that removes links to the old style django admin, and in places adds a number of links to the last actions that non-staff users might have needed the old admin for.
=> Add flag to hide admin and add ancillary links

greenweb/settings/development.py
By adding `.gitpod`, in `ALLOWED_HOSTS` we should now be able to spin up gitpod instances without the scary NOT ALLOWED error from before.
=> Extend ALLOWED_HOSTS to support Gitpod

apps/accounts/templates/provider_registration/base_form.html, apps/accounts/templates/provider_registration/consent.html, apps/accounts/templates/provider_registration/evidence.html, apps/accounts/templates/provider_registration/locations.html, apps/accounts/templates/provider_registration/network_footprint.html, apps/accounts/templates/provider_registration/partials/_location_form.html, apps/theme/static_src/src/css/custom/forms-custom.css, apps/theme/static_src/src/css/custom/forms.css
Following our upgrade to a newer version of Django, some of our form layouts have changes and look a bit wonky.
This PR seeks to address those issues and get our forms looking nice again.
=> WIP: Form layout fixes

.github/workflows/run-tests.yml
Hey @mrchrisadams ,
we have massively slimmed our Eco-CI tool and wanted to bring you the lastest update via PR.
- Moving from `@main` inclusion to `@VERSION`. This will instruct Dependabot to also make PRs automatically in the future in case we update Eco-CI.
- Using the newest super slim v4.0-rc3 version. Find all details like a 100x improvement here: https://github.com/green-coding-solutions/eco-ci-energy-estimation/releases/tag/v4.0-rc3
- We now require `machine-uuid` to be set. I generated a random one for you that you can then find in your CarbonDB view: https://metrics.green-coding.io/carbondb-lists.html?company_uuid=7f1d34f0-7666-4378-8d8f-d37cced7ccb0
- Note there: They way this was defined in the PR was sadly incorrect. Probably my bad. But Eco-CI did not pick up the CarbonDB …
=> Moving to v4.0-rc3 and added machine-uuid

greenweb/settings/production.py
This PR catches to the two noisest sets of errors we started seeing recently when a connection to RabbitMQ is unexpectedly closed.
Dramatiq, our queueing library handles these, so logging them to Sentry is needlessly noisy and wasteful.
=> Add filter for main already-caught pika errors

apps/accounts/views.py
When removing the unused flags, the last PR related to this work, #610 (i.e. Remove old, unneeded flags), was a tad overzealous, and removed a flag called called "dashboard" from three years ago. 
This was the flag that hid some of the older involved charts we never released, and users who visited the the application root, at `/` could either be able to see the new stats, or be redirect to the shiny new provider portal.
This had the effect of showing the screen below that would only be showed when the dashboard flag was active:
This PR redirects user to the provider portal view, restoring the previous behaviour, so visiting `/` when authenticated shows you something like this again:
=> Add the redirect to the provider portal again

ansible/deploy.yml, ansible/see_command_output.yml
This PR adds the 5th app server we use in our system, so we can refer to it explicitly when running commands against it with `see_command_output.yml` or in focussed deploys.
We used it when switching from making an external DNS lookup to reach our database server i.e. looking up `db2.greenweb.org` to the private IP address that all the app servers can reach whilst on the same shared private network with Hetzner.
Previously we were seeing connectivity issues as the app servers would sometimes be unable to resolve db2.greenweb.org to the public IP address. 
The change isn't visible here, but we have also updated our database connection string to use the private IP address instead of the public domain name and public IP address too.
We do the same with our Rabbit MQ connection, as we have …
=> Add reference to 5th app server for running ansible commands

ansible/deploy.yml, ansible/see_command_output.yml, apps/accounts/admin_site.py, apps/accounts/templates/emails/verification-request-notify.html, apps/accounts/templates/emails/verification-request-notify.txt, apps/accounts/templates/provider_portal/before_starting.html, apps/accounts/templates/provider_portal/request_detail.html, apps/accounts/tests/test_provider_portal.py, apps/accounts/tests/test_provider_request.py, apps/accounts/views.py, apps/greencheck/tests/models/test_greencheck_stats.py, apps/greencheck/tests/test_directory.py, apps/greencheck/views.py, apps/theme/templates/greencheck/partials/_directory_beta-msg.html, apps/theme/templates/greencheck/partials/_directory_results.html, docs/index.md, docs/requirements.txt, docs/troubleshooting.md, greenweb/settings/production.py, requirements/requirements.dev.in
This tiny PR improves the filtering of providers when the Directory list is rendered.
The previous logic would only exclude providers who were marked as `showOnWebsite=false`. This exposed an edge case where providers might be archived (`archived=true`) however might still have the showOnWebsite variable set to true (`showOnWebsite=true`). In this case the provider would incorrectly be shown on the Directory even though they are archived.
This PR fixes that.
=> Improve directory filtering to exclude archived providers

apps/greencheck/views.py
This update improves the filtering applied when generating the list of providers to show in the Directory.
It adds a condition to ignore all archived providers.
=> Ignore archived providers in Directory

apps/accounts/admin.py, apps/accounts/models/provider_request.py, apps/accounts/tests/test_provider_ip_range.py
This PR includes a calculation of the IP range size when verifying a request. This is helpful for cases when a provider accidentally adds a larger than intended range.
=> Show the size of an IP range

apps/accounts/admin_site.py, apps/greencheck/tests/views/test_api_carbon_txt.py
This pull request introduces the use of feature flags to control access to the CarbonTxt preview functionality. It adds the `WaffleFlagMixin` to the `CarbonTxtCheckView` class and includes tests to ensure the feature flag works as expected.
Feature flag implementation:
* [`apps/accounts/admin_site.py`](diffhunk://#diff-b831cb223efc314cdde38f09df715e010ce7f38af3a9d55b59810e01472ac979L15-R15): Added `WaffleFlagMixin` to `CarbonTxtCheckView` and set `waffle_flag` to "carbon-txt-preview". [[1]](diffhunk://#diff-b831cb223efc314cdde38f09df715e010ce7f38af3a9d55b59810e01472ac979L15-R15) [[2]](diffhunk://#diff-b831cb223efc314cdde38f09df715e010ce7f38af3a9d55b59810e01472ac979L91-R95)
Testing enhancements:
* [`apps/greencheck/tests/views/test_api_carbon_txt.py`](diffhunk://#diff-a82d34405ceea36496850c …
=> Put the carbon-txt-preview route behind a flag

.devcontainer/devcontainer.json, justfile
This PR updates the devcontainer file used to define what is built when spinning up a codehub codespace.
It also adds a slightly more convenient Justfile, for running django management commands and using Marimo for data analysis
=> Update github codespace and justfile

apps/greencheck/domain_check.py, apps/greencheck/tests/test_domain_checker.py
This pull request includes updates to the `apps/greencheck` module to handle additional ASN-related exceptions and improve the robustness of the domain checker. The most important changes include expanding the list of exceptions handled in the `check_for_matching_asn` method and updating the corresponding tests to ensure all new exceptions are properly caught and logged.
* [`apps/greencheck/domain_check.py`](diffhunk://#diff-962c7da672ccda34a8739839ced1c68a0a9123743e584e2af98cbcc9a6c30154L26-R32): Added new ASN-related exceptions (`ASNRegistryError`, `ASNOriginLookupError`, `ASNLookupError`) to the import list and updated the `check_for_matching_asn` method to handle these exceptions. [[1]](diffhunk://#diff-962c7da672ccda34a8739839ced1c68a0a9123743e584e2af98cbcc9a6c30154L26-R32) …
=> Add richer set of errors caught

apps/greencheck/api/views.py, apps/greencheck/domain_check.py, apps/greencheck/exceptions.py, apps/greencheck/models/checks.py, apps/greencheck/serializers.py, apps/greencheck/tests/test_domain_claim.py, apps/greencheck/tests/views/test_api_domain_claim.py, greenweb/urls.py, justfile, pyproject.toml, uv.lock
This PR introduces new _domain claim_ logic where the platform now attempts to verify a domain is associated with a provider by looking for the existence of a domain, and a domain hash derived from a combination of the domain and a secret value already associated with the provider.
This allows for programatically associating domain with a provider by either:
1. adding a special `via` header to the HTTP response headers for requests served at `hosted-website.com`
2. adding a DNS TXT record for the domain being looked up, to associated say... `hosted-website.com` with the provider
The first is intended to cover the case of a managed service provider already registered with the platform wanting to have their platform's sustainability credentials showing up when `hosted-website.com` is looked …
=> Add domain claim support for #638 

apps/accounts/models/hosting/__init__.py, apps/accounts/models/hosting/abstract.py, apps/accounts/models/hosting/datacenter.py, apps/accounts/models/hosting/provider.py
That `hosting.py[ was getting quite unwieldy at over 1100 LOC, so i've had
a go at splitting it up: the external interface stays the same (as we
reexport everything used elsewhere in the codebase), but now the
"hosting" models are divided into a "datacentres" sub-package, a
"providers" sub-package, and an "abstract" sub-package for abstract
base classes shared by both. The "providers" package is still pretty
huge, at 700 LOC, but I think this makes things a little more
manageable, with room for further improvement.
@mrchrisadams, what do you think? This is meant as a bit of a
conversation-starter as much as anything - would you like to see some of
the larger files split up, or are you happy with everything in one
place?
=> Refactor accounts models

apps/accounts/admin.py
One thing I realised when looking at verification requests in the a django admin was that it's not too easy to see all the requests made by a provider.
This introduces the ability to filter by the either the provider name, or the website.
The former make it easier to match a given provider, and the latter allows for cases when you have two providers with similar names, or when want to see all the providers who use the same tld, like `.nl` or `.com`
=> Add ability to filter provider / verification requests via search

ansible/templates/import_ips_for_large_providers.sh.j2
Now we have archived the AWS provider, we don't want to update its IP ranges, as newly imported IPs are set as "active" leading to false positive "green" results.
See [this trello ticket](https://trello.com/c/0HcANMXF/555-aws-ip-ranges-still-active-returning-green-results-in-check?search_id=abcc8eb9-3ce2-4c61-bb30-c00253ca621f) for more details.
=> Don't run the AWS network importer

ansible/templates/import_ips_for_large_providers.sh.j2, apps/greencheck/exceptions.py, apps/greencheck/importers/network_importer.py, apps/greencheck/management/commands/update_networks_in_db_amazon.py, apps/greencheck/management/commands/update_networks_in_db_google.py, apps/greencheck/management/commands/update_networks_in_db_microsoft.py, apps/greencheck/tests/test_importer_amazon.py
This pull request introduces a new exception to handle cases where data import is attempted for an archived hosting provider, along with the necessary updates to enforce this behavior and tests to validate it. The changes ensure better error handling and maintain data integrity by preventing imports for archived providers.
* Added `ImportingForArchivedProvider` exception in `apps/greencheck/exceptions.py` to handle cases where data import is attempted for an archived provider. This includes a default error message and code.
* Modified `process_addresses` in `apps/greencheck/importers/network_importer.py` to check if the hosting provider is archived. If archived, it logs a warning and raises the new `ImportingForArchivedProvider` exception.
* Imported the new exception in …
=> Add test to catch importing for archived providers

ansible/setup_cronjobs.yml, ansible/templates/clear_archived_domains.sh.j2
one missing piece of the jigsaw in #658 was a cronjob to actually run the "archived greendomain purger" task periodically. This corrects that oversight :-)
=> Add a cron job to clear archived domains

ansible/deploy-workers.yml
This was failing due to some broken indentation, and overriding some variable names that shouldn't have been overridden.
=> Fix the deploy-workers ansible playbook

.devcontainer/codespaces-compose.yaml, apps/accounts/models/hosting/provider.py, apps/accounts/templates/emails/migration_email.txt, apps/accounts/templates/emails/new-linked-domain-notify.html, apps/accounts/templates/emails/new-linked-domain-notify.txt, apps/accounts/templates/emails/verification-request-notify.html, apps/accounts/templates/emails/verification-request-notify.txt, apps/accounts/tests/test_provider_request.py, apps/accounts/utils.py, apps/greencheck/swagger.py, greenweb/settings/common.py, templates/partials/nav_menu.html
Updates the support mailbox address to the new `@greenweb` domain.
The change applies to:
- Email templates
- Email sending functions
- Some page partials
This PR also includes a small update to the GitHub Workspaces compose file:
- Updates the image version to `universal:3`
This change was made because the initial build using `universal:2` was failing. Using `universal:3` the Codespace gets created successfully, however it does take around 8 minutes for this complete!
=> Update support email

.github/actions/setup-environment/action.yml, ansible/_install_deploy_dependencies.yml, pyproject.toml, uv.lock
Ansible 2.19 introduces some breaking changes which make the deploy fail - we should pin the version for now (and ensure when the deploy script calls UV it respects the lockfile) to avoid breaking the build.
=> Pin ansible version
