apps/accounts/admin.py
apps/accounts/filters.py

Adds a few filters for the hosting admin.

Add filters for partner, show on website and countries

---

apps/accounts/admin_site.py
apps/accounts/templates/try_out.html

Adds a view in admin so that you can check urls there as well. It was a request from Rene.

Be able to check an url in admin

---

apps/accounts/management/commands/migration_email.py
apps/accounts/templates/emails/migration_email.txt
greenweb/settings/common.py

The email that we want to send out to all users when we make the switch. @homepinr Let me know if you've got any comments on this.

Add migration email to be sent out to all users when we are ready

---

apps/greencheck/templates/backfill_procedure.sql
apps/greencheck/templates/insert_url_procedure.sql
apps/greencheck/templates/presenting.sql

We discussed in #36 what needed to be done. So after this is merged it will close #36 
To get this updated, all that you should need to do would be to run the management command `insert_procedures` again

Some improvements for the procedure

---

Pipfile
Pipfile.lock
README.md
apps/accounts/admin_site.py
apps/greencheck/management/commands/dump_greenpresenting.py
apps/greencheck/templates/green_url.html
apps/greencheck/views.py
greenweb/settings/common.py
greenweb/settings/production.py

So this PR does two things
* Creates a management command that dumps the data from the presenting table. 
* Creates a view where you can view all recent datadumps. 
For production we need to create to add the environment variable `GOOGLE_APPLICATION_CREDENTIALS` together with the path to the json credential. 
This PR closes #35

Dump the data + Present where you can download it

---

apps/accounts/admin.py

Filter non-staff users so we don't leak user data

---

apps/accounts/admin.py

This should address the issue where we show too many permissions, that I reported yesterday.

Ca fix admin switches for #55

---

.coveragerc
.travis.yml
Pipfile
pytest.ini

This PR adds coverage checking, to the testing setup, as described in  #14 .
You can read more about coverage here:
https://pytest-cov.readthedocs.io
This at least gives an idea if the key paths are covered.

Add coverage check to pytest

---

apps/accounts/admin.py
apps/accounts/filters.py

This PR adds date filters for listing hosters, as listed in #79.

First pass at adding date filters in admin

---

apps/accounts/filters.py

This PR:
- make the classes DRYer, using a mixin instead of inheritance
- uses a range filter query instead of two filters (thanks @jonathan-s  👍 )
- adds tests!

Refactor the year filters

---

greenweb/settings/common.py
templates/admin/accounts/hostingprovider/change_form.html
templates/admin/accounts/hostingprovider/hosting_provider_fieldset.html

This incorporates information about the associated user for a given hosting provider in the admin view.
With this, it's possible to see who the user is would receive any emails, as well as when they last logged in.

Show user for a given hosting provider

---

README.md

- Just a couple of minor spelling changes and one spacing change to correctly render the h3 in the top level README.

Spelling modifications and h3 spacing fix

---

ansible/deploy.yml
ansible/templates/nginx.conf.j2
ansible/templates/supervisor.gunicorn.conf.j2
ansible/templates/supervisor.worker.conf.j2
makefile

This PR:
- Adds a single command for deployments to production
- introduces updated supervisor templates

Deploy process tweaks

---

apps/greencheck/admin.py

This PR adds listings of 'created' and 'modified' dates in the admin view, as referred to in #82

Add date fields for ASN and IP ranges

---

apps/greencheck/management/commands/dump_green_domains.py

https://github.com/thegreenwebfoundation/admin-portal/issues/116

Resolves #116: Ensure uploaded DB dumps are public

---

greenweb/urls.py

Add redirect to account for split of admin from green-urls

---

apps/theme/templatetags/admin_helpers.py
apps/theme/test_admin_helpers.py
templates/admin/accounts/datacenter/change_form.html
templates/admin/accounts/datacenter/fieldset.html

This PR introduces a link to the site from admin, making it easier to visit from when reviewing info.

Add links to website in admin

---

apps/accounts/forms.py

We likely need to use a separate form outside of admin.

Fix the 500 exception from removing password field

---

apps/greencheck/models/stats.py
apps/greencheck/tests/models/test_greencheck_stats.py

These methods are quite expensive to run timewise, so we run them on cronjobs or in a worker.
Previously running them more than once could end up making two sets of stats, which looked funny in charts, and gave misleading figures.
This change means we can run the same command for the same day multiple times, without duplicating the stats we present.

Make stat creation methods idempotent

---

.github/workflows/run-tests.yml
apps/accounts/admin.py
apps/accounts/tests/test_admin.py
apps/accounts/tests/test_form.py
apps/greencheck/admin.py
apps/greencheck/forms.py

This PR introduces some testing around our use of admin forms, to catch the errors we saw reported by users when trying to update IP ranges.

Fix Ip range save bug - resolves #184

---

.github/workflows/run-tests.yml
apps/accounts/admin.py
apps/accounts/tests/test_admin.py
conftest.py

This PR adds tests to check that visiting our datacentre update pages render okay, as well as fixing a issue reported by users and expanded in #186 186

Datacenter forms

---

apps/greencheck/viewsets.py

This PR introduces a safer callback so when rabbitMQ, our message queue is not available we are still able to serve traffic.
The tradeoff is that the updates are not logged to RabbitMQ, so we lose the checks but that is better than not being  able to serve traffic, and in the worst case scenario we are still able to reconstruct requests by looking at nginx  logs.

Handle missing rabbitmq

---

.env.gitpod
.gitpod.dockerfile
.gitpod.yml

This PR introduces gitpod for cloud based development environments.
This should make it easier to get started, and avoid needing to deal with so many local setup issues.

WIP Ca gitpod dev setup

---

Pipfile
Pipfile.lock
apps/greencheck/domain_check.py
apps/greencheck/tests/test_domain_checker.py
conftest.py

This PR fixes the case when looking up a green domain, we are unable to find a corresponding provider

Fix empty green domain results

---

.gitpod.yml
apps/accounts/admin_site.py
apps/accounts/templates/try_out.html
apps/greencheck/domain_check.py
apps/greencheck/tests/test_greencheck_tryout.py
conftest.py

Finally adding the more advanced checks as outlined in #66

Start reimplementing the detailed checks again.

---

Pipfile
Pipfile.lock
README.md
docs/Makefile
docs/conf.py
docs/deployment.md
docs/index.md
docs/installation.md
docs/key-concepts.md
docs/make.bat
env.sample

This adds the use of sphinx and specifically the Furo theme, for technical documentation of the platform.

Add documentation using sphinx

---

docs/other-greenweb-software.md
docs/working-with-greenweb-datasets.md

This should stop the errors reported by Sphinx.
@roald-teunissen can you look over and merge it in? 
Once you have this, you'll have both made a PR and accepted a PR pushing the changes to public sites.

Fix broken links to external websites

---

docs/deployment.md
docs/general.md
docs/how-to.md
docs/index.md
docs/installation.md
makefile

Initial structure and added installation, deployment, general and how to.

First revision of the documentation.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/discussion.md
.github/ISSUE_TEMPLATE/feature_request.md

Three basic templates that can help structure our issue list in Github. We can add more in the future if needed, but for now this is a good start.

Update issue templates

---

.env.gitpod
pytest.ini

Hey @roald-teunissen  - I've created this PR to make sure that pytest always uses the testing module now.
This should help with the error you saw today.

Update pytest to always use testing settings module

---

.env.gitpod

Gitpod crashes on startup without these

Add missing env vars for gitpod

---

apps/greencheck/api/legacy_views.py
apps/greencheck/tests/test_legacy_v2_api.py

[Check this issue.](https://github.com/thegreenwebfoundation/admin-portal/issues/266)

Implemented ordering functionality for providers in directories

---

apps/greencheck/tests/test_carbon_txt.py
apps/greencheck/workers.py

This fix should resolve the issue with logging carbon.txt lookups

Fix carbon txt log error fixes #281

---

.gitpod.yml
docs/installation.md

This PR extends our gitpod dev environment to add
1. more build steps run automatically
2. mailhog for testing mail in development
3. any last checks to enable connecting to staging environments

Add mailhog, and extra build steps resolves  #288

---

docs/requirements.txt

See issue #293 about the breaking doc build

Update the dependencies for read the docs

---

docs/how-we-check-for-green.md
docs/index.md
docs/installation.md
docs/other-greenweb-software.md
docs/working-with-greenweb-datasets.md

Updated the developer-facing documentation:
- fixed some typos
- fixed formatting in some cases
- added more info about setting up on local machine
- simplified instructions for `pipenv`

Dev docs fixes

---

Pipfile
Pipfile.lock
ansible/deploy.yml
ansible/inventories/prod.yml
ansible/templates/run_worker.sh.j2
apps/greencheck/object_storage.py
apps/greencheck/tasks.py
docs/deployment.md
one_day_to_parquet.py

This PR adds support for multiple app servers to take the load off the single main box we have been running requests from, and also adds new dramatiq tasks, for creating parquet files from the massive greencheck table for analysis

Ca greencheck parquet

---

.github/workflows/run-deploy-staging.yml
ansible/_add_system_dependencies.yml
ansible/deploy.yml
ansible/fetch_snapshot_for_import.yml
ansible/inventories/dev.yml
ansible/inventories/prod.yml
ansible/inventories/staging.yml
ansible/provision_app.yml
ansible/templates/clear_and_import.sql.j2
ansible/templates/dotenv.j2
env.sample

this PR re-introduces a staging environment, so when we push to `staging` on github , we trigger a deploy to our staging servers, without needing to run ansible tasks manually

Set up a staging environment 

---

apps/greencheck/README.md

This document has been created to provide anyone who might come across this code with some relevant information with regards to what they are looking at. It providers guides to documentation resources, data sets, as well as links to the important files in this repository.

Create readme for API docs folder

---

apps/accounts/templates/provider_request/list.html

Please have a look at my new link to make the start of the reg process actually a thing

New registration button links to form start

---

docs/how-to.md
docs/index.md

I added a link to Sentry in the developer docs

Document access to Sentry

---

apps/accounts/forms.py
apps/accounts/templates/provider_registration/services.html

I've used the suggested implementation for `mark_safe` that Chris and Oliwia helped me with here: https://github.com/thegreenwebfoundation/admin-portal/issues/374
Could I get a code review to make sure you are happy with how I have implemented it please? Thanks :smile:

Shuffle services intro and help text around

---

apps/accounts/templates/provider_registration/preview.html
apps/accounts/templates/provider_request/detail.html
apps/accounts/views.py
apps/theme/static_src/src/css/base.css
apps/theme/static_src/src/css/components.css
apps/theme/templates/style-guide.html

Add some alerts to verification form, and add styles to our style-guide for later reference.

Alert styling

---

apps/accounts/templates/emails/activation.html
apps/accounts/templates/registration.html

Amend text on signup page and activation email.

Signup copy tweaks

---

apps/greencheck/admin.py

Remove non-staff add and view permissions. Fixes #426

---

apps/accounts/models/provider_request.py
apps/accounts/templates/provider_request/detail.html

Small rendering changes to the detail view of the verification request.
Before and after screenshots:

Tweaks: request detail view

---

apps/accounts/forms.py
apps/accounts/tests/test_form.py

Scope:
- change error message and help text on the locations step in the verification form,
- add test
Result:

Clarify that 1 location is required when bulk import option is selected

---

apps/accounts/forms.py
apps/accounts/templates/emails/verification_request_approved.html
apps/accounts/templates/emails/verification_request_approved.txt

Based on feedback from the following Trello cards:
- https://trello.com/c/bOOt1WrQ/142-verification-form-if-you-check-the-bulk-import-option-on-the-location-page-you-still-have-to-add-a-location
- https://trello.com/c/DL6vAZgm/143-verification-form-amend-error-message-on-evidence-section
- https://trello.com/c/69Vrbfkw/154-verification-form-automated-approval-email-when-verification-is-approved

Wording fixes: verification request form and email

---

apps/accounts/templates/provider_request/detail.html

Based on the feedback in these Trello cards: 
- https://trello.com/c/nLYb4FSp/148-verification-form-tweaks-to-request-summary-view
- https://trello.com/c/NQsv6yaS/164-edit-summary-of-pending-verification-request-to-guide-a-user-on-how-to-edit-their-information

Formatting fixes on the verification request detail page

---

apps/accounts/templates/provider_portal/request_detail.html

Addresses feedback from this card: https://trello.com/c/NQsv6yaS/164-edit-summary-of-pending-verification-request-to-guide-a-user-on-how-to-edit-their-information

Open link to the support form in a new tab

---

apps/accounts/templates/emails/verification_request_approved.html
apps/accounts/templates/emails/verification_request_approved.txt

Addresses feedback from this card: https://trello.com/c/69Vrbfkw/154-verification-form-automated-approval-email-when-verification-is-approved

Update copy of verification request approval email: how to download the badge

---

apps/accounts/templates/provider_portal/home.html

This PR adds the link back to the old admin screen for folks who need it to carry out some specific actions

Add link to admin screen again

---

apps/accounts/views.py
greenweb/settings/common.py

This should be merged as a part of the soft launch of the verification request form

Redirect logged in users to provider portal

---

apps/accounts/templates/base.html
apps/accounts/templates/provider_portal/before_starting.html
apps/accounts/templates/provider_portal/home.html
apps/accounts/templates/provider_portal/request_detail.html
apps/accounts/templates/provider_registration/preview.html
apps/accounts/urls.py
apps/accounts/views.py

Need to test on STAGING, so merging this branch to do that.

Hs copy tweaks

---

apps/accounts/management/commands/check_providers_and_expiry_dates.py
apps/accounts/models/hosting.py

This PR introduces a management command, and a convenience function for looking at coming expiry dates for providers.
It seemed like something we'd want to project forwards so we know when we can predict expected workload for our support desk

Add commands for easier tracking of data quality

---

apps/greencheck/views.py
apps/theme/static_src/src/css/base.css
apps/theme/templates/greencheck/directory_index.html
apps/theme/templates/greencheck/partials/_directory_ctas.html
apps/theme/templates/greencheck/partials/_directory_results.html

A few very small tweaks based on the teams feedback.
https://trello.com/c/bqwl52XC/257-directory-team-feedback

Hs team feedback tweaks

---

apps/theme/templates/base_directory.html
apps/theme/templates/greencheck/partials/_directory_beta-msg.html
apps/theme/templates/greencheck/partials/_directory_ctas.html
apps/theme/templates/greencheck/partials/_directory_footer.html
apps/theme/templates/greencheck/partials/_directory_results.html

A few small changes to styling and copy pre-launch of Directory.
https://trello.com/c/4NNvupdX/240-directory-make-header-logo-and-directory-text-link-back-to-directory
https://trello.com/c/WIYHBFnG/280-directory-beta-message-at-the-top
https://trello.com/c/PocB93aS/281-directory-ensure-anchor-links-to-providers-spit-you-to-a-useful-part-of-their-listing

Hs pre mvp launch changes

---

apps/accounts/templates/provider_portal/home.html

https://trello.com/c/cTwHT8PB/318-solicit-donations-on-the-portal-homepage

Add a support the mission box

---

apps/theme/templates/base_directory.html
apps/theme/templates/greencheck/directory_index.html
apps/theme/templates/greencheck/partials/_directory_ctas.html
apps/theme/templates/greencheck/partials/_directory_results.html

https://trello.com/c/tmLOntYw/312-directory-back-to-top-button-missing

Hs directory to top button

---

apps/accounts/admin.py
apps/accounts/templates/emails/verification-request-notify.html
apps/accounts/templates/emails/verification-request-notify.txt
apps/accounts/templates/emails/verification_request_approved.html
apps/accounts/templates/emails/verification_request_approved.txt
apps/accounts/tests/test_provider_request.py
apps/accounts/views.py

The main purpose of this PR is to update the content of the verification approval email for new providers. The aim is to provide more useful links and structured guidance on how providers can manage their approved listings.
Another change included in this PR is to dynamically adjust the email subject for verification request & approval emails to indicate if they are "new requests" or "updates".

Update verification email copy

---

ansible/setup_cronjobs.yml
ansible/templates/import_ips_for_large_providers.sh.j2
docs/recurring-tasks.md

This PR changes the import script so it can be run from any directory not just inside the application directory

Fix path, and add extra bash good practice flags

---

apps/greencheck/tests/test_domain_checker.py
apps/theme/templatetags/admin_helpers.py
apps/theme/test_admin_helpers.py

This should resolve the issue reported by Sentry in PR #575

Fix bug in admin triggered by new domain lookup code

---

docs/installation.md
makefile

This PR adds to the docs for people coming to the codebase for the first time, and adds extra information to the makefile

Add extra docs after pairing on set up with Han

---

apps/accounts/templates/emails/verification-request-notify.html
apps/accounts/templates/emails/verification-request-notify.txt
apps/accounts/templates/provider_portal/request_detail.html

🤔  Longest PR title ever?
This PR makes two small text changes to the admin portal. The text changes reflect that from July, 2024 we will begin reviewing new verification requests and updates as a batch every Tuesday each week. The purpose of this change is to help set expectations for folks who submit verification requests.
Text has been changed in:
- TEXT version of verification email
- HTML version of verification email
- Final (details) page of new Form wizard

Update wording of portal and verification emails to reflect batch reviewing of requests

---

docs/index.md
docs/requirements.txt
requirements/requirements.dev.in

This PR updates our docs to include the new guidance for handling exceptions along with other recent docs that were not in the index

Update docs to include new guidance

---

apps/theme/templates/greencheck/partials/_directory_beta-msg.html
apps/theme/templates/greencheck/partials/_directory_results.html

https://trello.com/c/4gNCpQCk/326-link-to-i-think-theres-an-error-in-the-dataset-faq-from-new-directory
This task has been trigged by the FAQ we have [I think there’s an error in the Green Web Dataset, what can I do?](https://www.thegreenwebfoundation.org/support/i-think-theres-an-error-in-the-green-web-dataset-what-can-i-do/).
Also as we've just about finished our data quality overhaul, it's a good idea to look at the "Help improve this listing" text shown on the most scant of our Directory listings.

WIP: Rewrite “Help improve this listing” text in the Directory

---

docs/working-with-docker.md

We've had reports it isn't working, and until we have it resolved, it's better to warn people than have them waste their time on it.

Add warning that docker is not working

---

.gitignore
apps/accounts/forms.py
apps/accounts/templates/provider_portal/partials/provider_listing.html
apps/accounts/templates/provider_portal/provider_domain_detail.html
apps/accounts/templates/provider_portal/provider_domain_new/base.html
apps/accounts/templates/provider_portal/provider_domain_new/step_1.html
apps/accounts/templates/provider_portal/provider_domains_index.html
apps/accounts/validators.py

This PR makes only text updates to the various pages that have been added to facilitate linking domains to hosting providers.
All the changes have been made to the user facing wizard & details pages. Not changes have been made to the internal platform pages.

Update copy for linking domains
